[package]
name = "viem-core"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/core/lib.rs"
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "=1.0.114"
encoding_rs = "=0.8.35"
html5ever = "=0.39.0"
regex = "1.11"
regex-automata = "=0.4.18"
regex-syntax = "=0.8.11"
unicode-linebreak = "=0.1.5"
unicode-segmentation = "=1.12.0"
unicode-bidi = { version = "=0.3.18", default-features = false, features = ["hardcoded-data"] }

[dev-dependencies]
