//! Seed documents for the consistency fuzzer. Markdown seeds deliberately
//! include degenerate, malformed and ambiguous spellings; every entry is opened
//! both as Markdown WYSIWYG and as Markdown Source.

pub const MARKDOWN: &[&str] = &[
    // Empty and whitespace-only documents.
    "",
    "\n",
    "\n\n",
    "\n\n\n\n",
    " ",
    "   \n  \n",
    "\t",
    "a",
    "a\n",
    "a\n\n",
    "\na",
    "\n\na\n\n",
    "a\nb",
    "a\n\nb",
    "a\n\n\n\nb",
    "a  \nb",
    "a\\\nb",
    "a<br>b",
    "a\r\nb\r\n\r\nc",
    "a\rb\r\rc",
    // Headings.
    "# Heading",
    "#",
    "# ",
    "#\n",
    "##",
    "####### seven",
    "# Heading #",
    "# Heading ###   ",
    "#Not heading",
    "\\# not heading",
    "Setext\n===",
    "Setext\n---",
    "Setext\nline two\n===",
    "===",
    "a\n=\n\nb",
    "# A\n## B\n### C\n#### D\n##### E\n###### F",
    "# **Bold** heading\n\ntext",
    "# `code` heading",
    "> # quoted heading",
    "- # list heading",
    // Emphasis and inline syntax.
    "**bold**",
    "*it*",
    "_it_",
    "__bold__",
    "***both***",
    "**a *b* c**",
    "*a **b** c*",
    "**unclosed",
    "*unclosed",
    "unopened**",
    "a**b**c",
    "a*b*c",
    "snake_case_word",
    "**",
    "****",
    "* *",
    "** **",
    "~~strike~~",
    "~strike~",
    "~~unclosed",
    "`code`",
    "``code with ` tick``",
    "`unclosed code",
    "``",
    "` `",
    "a `b` c `d` e",
    "**`code in bold`**",
    "`**not bold**`",
    "<ins>under</ins> <sup>sup</sup> <sub>sub</sub>",
    "<ins>unclosed",
    "</ins>",
    "x<sup>2</sup>",
    "&amp; &lt; &gt; &quot; &#35; &#x41; &nbsp;",
    "&bogus; &#xZZ; &",
    "\\*escaped\\* \\_x\\_ \\` \\\\ \\#",
    "trailing backslash\\",
    "line  \n  \nafter double space",
    // Links and images.
    "[link](https://example.com)",
    "[link](https://example.com \"title\")",
    "[](empty)",
    "[text]()",
    "[unclosed](url",
    "[unclosed",
    "]stray[",
    "[a][ref]\n\n[ref]: https://example.com",
    "[ref]\n\n[ref]: /url",
    "[ref]: /url",
    "[ref]: /url \"title\"\n[other]: <x y>",
    "<https://auto.link>",
    "https://bare.link.example",
    "<mailto:a@b.c>",
    "![img](local.png)",
    "![](local.png)",
    "![alt](https://remote.example/x.png)",
    "a ![img](i.png) b",
    "![img](i.png)\n\n![img2](j.png)",
    "[![img](i.png)](https://x.y)",
    "**[bold link](u)**",
    "[**bold** in link](u)",
    "[`code` link](u)",
    "[a](u)[b](v)",
    "<img src=\"a.png\" width=\"10\">",
    // Lists.
    "- a",
    "- ",
    "-",
    "- a\n- b\n- c",
    "* a\n+ b\n- c",
    "1. a\n2. b\n3. c",
    "1) a\n2) b",
    "3. a\n4. b",
    "0. zero",
    "1. a\n1. b\n1. c",
    "- a\n  - b\n    - c\n      - d\n        - e",
    "- a\n\n- b",
    "- a\n\n  continued\n- b",
    "- a\ncontinued lazily\n- b",
    "- a\n- \n- c",
    "- \n- \n- ",
    "1. \n2. ",
    "- [ ] task\n- [x] done",
    "- [ ]\n- [x]",
    "- a\n\n\n- b",
    "- a\n1. b",
    "1. a\n   - b\n2. c",
    "- a\n  ```\n  code\n  ```\n- b",
    "- > quote in list",
    "- | a | b |\n  | - | - |\n  | 1 | 2 |",
    "-\ta\n-\tb",
    "- a\n    - over-indented",
    "10. ten\n11. eleven",
    "999999999. big",
    "- a\nb",
    "text\n- list right after text",
    "text\n1. list after text",
    "text\n2. not a list",
    "- a\n  b\n  c",
    "    - indented code not list",
    // Block quotes.
    "> quote",
    ">",
    "> ",
    ">quote",
    "> a\n> b",
    "> a\nlazy",
    "> a\n\n> b",
    "> a\n>\n> b",
    ">> nested",
    "> > nested\n> back",
    "> - list in quote\n> - b",
    "> ```\n> code\n> ```",
    "> | a | b |\n> | - | - |\n> | 1 | 2 |",
    "> # h\n> text",
    "> a\n---",
    // Code blocks.
    "```\ncode\n```",
    "```",
    "```\n",
    "```\n```",
    "```rust\nfn main() {}\n```",
    "```\nunclosed fence\nmore",
    "~~~\ntilde\n~~~",
    "````\n```\nnested\n```\n````",
    "```\n\n\n```",
    "```\na\n\nb\n```\n\ntext",
    "    indented code",
    "    a\n\n    b",
    "\tTab code",
    "text\n    not code (lazy)",
    "``` info string with spaces\nx\n```",
    "```js\n// comment\nlet a = `template ${x}`;\n```",
    "text\n```\ncode\n```\ntext",
    "```\n| not | table |\n```",
    // Thematic breaks.
    "---",
    "***",
    "___",
    "- - -",
    "a\n\n---\n\nb",
    "a\n***\nb",
    "---\n---",
    "---\ntitle: front matter\n---\n\nBody",
    // Tables.
    "| a | b |\n| - | - |\n| 1 | 2 |",
    "| a | b |\n|---|---|\n| 1 | 2 |\n| 3 | 4 |",
    "a | b\n- | -\n1 | 2",
    "| a |\n| - |\n| 1 |",
    "| a | b |\n| - | - |",
    "| a | b |\n| :- | -: |\n| 1 | 2 |",
    "| a | b | c |\n| :-: | --- | ---: |\n| 1 | 2 | 3 |",
    "| a | b |\n| - | - |\n| 1 |",
    "| a | b |\n| - | - |\n| 1 | 2 | 3 |",
    "| a | b |\n| - | - |\n|  |  |",
    "| | |\n|-|-|\n| | |",
    "| a \\| pipe | b |\n| - | - |\n| `c|d` | e |",
    "| **bold** | _it_ |\n| - | - |\n| [l](u) | `c` |",
    "| a | b |\n| - | - |\n| 1 | 2 |\n\ntext after",
    "text before\n\n| a | b |\n| - | - |\n| 1 | 2 |",
    "text before\n| a | b |\n| - | - |\n| 1 | 2 |",
    "| a | b |\n| - | - |\n| 1 | 2 |\ntext lazily after",
    "| a | b |\n| - | - |\n| 1 | 2 |\n| a | b |\n| - | - |\n| 1 | 2 |",
    "| a | b |\n| - | - |\n| 1 | 2 |\n\n| c | d |\n| - | - |\n| 3 | 4 |",
    "| a | b |\n| -- | - |\n| é👩‍💻 | العربية |",
    "|a|b|\n|-|-|\n|1|2|",
    "| a | b\n| - | -\n| 1 | 2",
    "| a | b |\n| - |\n| 1 | 2 |",
    "| a |\n| --- |\n",
    "| x |\n|---|\n| ![i](i.png) |",
    "| a | b |\n| - | - |\n| 1<br>2 | 3 |",
    // Wide and complex tables (horizontal overflow, wrapping, inline syntax).
    "| one | two | three | four | five | six |\n|---|---|---|---|---|---|\n| 1 | 2 | 3 | 4 | 5 | 6 |\n| alpha | beta | gamma | delta | epsilon | zeta |",
    "Intro text.\n\n| Column A | Column B | Column C |\n| --- | --- | --- |\n| a long cell that will certainly wrap at narrow widths | b | c |\n| **bold** `code` | [link](u) | ~~s~~ |\n\nOutro text.",
    "| a | b |\n| - | - |\n| | |\n| x | |\n| | y |",
    "| a |\n| - |\n| 1 |\n| 2 |\n| 3 |\n| 4 |",
    "- item\n\n  | a | b | c | d |\n  |---|---|---|---|\n  | 1 | 2 | 3 | 4 |\n\n- next",
    "| `a|b` | c |\n| --- | --- |\n| d | e \\| f |",
    "| x | y |\n|:--|--:|\n| left | right |\n\n# After\n\nparagraph",
    // Second batch: degenerate and mixed constructs.
    "a\r\nb\nc\rd",
    "line one\r\n\r\nline two\n\nline three\r\rfour",
    "> - > - > a\n> - > - > b",
    "- > ```\n  > code\n  > ```",
    "1. > # heading\n   > text\n2. b",
    ">\tquote with tab",
    "-\tfoo\n\n\tbar",
    "*\ta\n*\tb",
    "\u{a0}leading nbsp",
    "a\u{a0}\u{a0}\nb",
    "last line backslash\\",
    "foot[^1] note\n\n[^1]: The note.",
    "[^1]: lone footnote definition",
    "<pre>\npre block\n\n</pre>\n\nafter",
    "<?php echo 1; ?>",
    "<!DOCTYPE html>",
    "<![CDATA[ x ]]>",
    "<table><tr><td>cell</td></tr></table>",
    "<!--\ncomment\n\nspanning\n-->",
    "[ref]: /url\n  \"title on next line\"\n\n[ref]",
    "[ref]:\n/url\n\n[ref]",
    "Setext\nlazy\n> quote\n===",
    "- a\n\n      indented code in list\n- b",
    "> ```\n> unclosed fence in quote\n\nafter",
    "````md\n```\ninner\n```\n````",
    "~~~\n```\n~~~",
    "**bold *nested _deep `code` deep_ nested* bold**",
    "*a*b*c*",
    "_a_b_c_",
    "a**b**c**d**",
    "***a** b*",
    "[link [nested] text](u)",
    "[a](<u v>) [b](u \"t\") [c](u 't') [d](u (t))",
    "![a](u \"t\")![b](v)",
    "\\[not link\\](u)",
    "`` ` ``",
    "` a `  `b`",
    "x<br/>\ny",
    "<b>\n\nbold across\n\n</b>",
    "$math$ and $$block$$",
    "- [ ] task\n  - [x] nested done\n- [X] upper",
    "1. one\n1. one\n1. one\n\n   para in third",
    "1. a\n\n\n2. b",
    "- a\n -  b\n  -   c",
    "+ plus\n+ list\n\n- minus\n- list",
    "a\n- \nb",
    "#heading-ish\n#\t tab heading",
    "  ## indented heading",
    "    ## code not heading",
    "Title\n=====\n\nSub\n---\n\nText",
    "| a |\n|:-:|\n| b |\n\n| c |\n|---|",
    "a|b\n-|-\nc|d",
    "| single |",
    "|---|",
    "| a | b |\n| --- | --- |\n| c | d |\n| e | f |\n| g | h |\n| i | j |\n| k | l |",
    // HTML.
    "<div>\nblock\n</div>",
    "<div>",
    "<!-- comment -->",
    "<!-- unclosed comment",
    "a <!-- inline --> b",
    "<span>inline</span>",
    "<b>bold</b> <i>it</i> <em>e</em> <strong>s</strong>",
    "<details><summary>s</summary>\n\nbody\n\n</details>",
    "<script>alert(1)</script>",
    "<p align=\"center\">x</p>",
    "a <br/> b <br> c",
    "<",
    "a < b > c",
    "<unknown-tag attr>",
    "</closing-only>",
    // Unicode and whitespace.
    "é👩‍💻🇨🇦 العربية עברית 中文",
    "e\u{301}\u{302}",
    "\u{200b}zero\u{200b}width",
    "nbsp\u{a0}here",
    "trailing spaces   ",
    "\t\ttabs\t",
    "mixed\u{2028}separator",
    "a\u{feff}b",
    "\u{fffd}",
    "**é**👩‍💻**ü**",
    "# العربية heading",
    "- عربي\n- עברית",
    // Combinations.
    "# Title\n\nPara **bold** and _it_.\n\n- a\n- b\n\n> q\n\n```\nc\n```\n\n| a | b |\n| - | - |\n| 1 | 2 |",
    "- a\n\n  > q\n\n  ```\n  c\n  ```\n\n- b",
    "> - a\n>   - b\n> - c",
    "1. a\n\n   | x | y |\n   | - | - |\n   | 1 | 2 |\n\n2. b",
    "a\n\n<div>\n\n**md inside html**\n\n</div>\n\nb",
    "Text with [link](u) and ![img](i.png) and `code` and **bold**.",
    "Line one\nLine two\nLine three",
    "**a\n\nb**",
    "*a\nb*",
    "[a\nb](u)",
    "`a\nb`",
    "a\n\n\n\n\n\nb",
    "- a\n\n\n\n- b",
    "# h\n\n\n\n# h2",
    "> a\n\n\n\n> b",
];

pub const CODE: &[(&str, &str)] = &[
    ("x.rs", ""),
    ("x.rs", "fn main() {\n    println!(\"hi\");\n}\n"),
    ("x.rs", "// comment\n/// doc\n/* block\n * star\n */\nfn f() {}"),
    ("x.rs", "\tlet a = 1;\n\n\n\tlet b = \"str\\\"ing\";"),
    ("x.py", "def f(x):\n    return x  # comment\n\n\nclass A:\n    pass\n"),
    ("x.py", "s = '''\nmulti\nline\n'''\n"),
    ("x.c", "#include <stdio.h>\nint main() { /* x */ return 0; }\n"),
    ("x.js", "const a = `t ${b}`;\n// x\nfunction f() {\n  return 1;\n}"),
    ("x.json", "{\n  \"a\": [1, 2, {\"b\": null}]\n}"),
    ("x.md", "# heading\n\n**bold** text\n\n```rust\nfn x() {}\n```\n"),
    ("x.html", "<html>\n<body>\n<p>x</p>\n</body>\n</html>"),
    ("x.sh", "#!/bin/sh\necho \"hi\" # c\nif [ -f x ]; then\n  y\nfi\n"),
    ("x.rs", "\n\n\n"),
    ("x.rs", "fn very_long_line() { let x = 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 + 13 + 14 + 15 + 16; }"),
    ("x.txt", "plain\n\ttext\n"),
];

pub const PLAIN: &[&str] = &[
    "",
    "\n",
    "a",
    "First paragraph.\nSecond line.\n\nLast line.",
    "e\u{301} 👩\u{200d}💻 🇨🇦 العربية עברית 中文\n\tTabs\0NUL\n",
    "a\r\nb\r\n",
    "\n\n\n",
    "   leading\ntrailing   \n",
    "**not markdown**\n# nope\n| a | b |",
];
