//! Curated portable filename rules, audited against Vim 9.2's filetype.vim
//! and autoload/dist/ft.vim and Viem's bundled syntax catalogue. See PROFILE.md.
//! These are data-only rules: startup never loads or executes Vim file detection.
//!
//! Keep these tables in sync when the Vim inventory, Tree-sitter packages or
//! language catalogue changes; follow PROFILE.md's language maintenance checklist.
//! Audit real extensions/basenames, use canonical catalogue IDs, and add detection
//! and opening tests. Document ambiguous omissions instead of guessing. Syntax
//! file stems and Tree-sitter query names are not automatic extension mappings.

fn exact(rules: &[(&str, &'static str)], value: &str) -> Option<&'static str> {
    rules.binary_search_by_key(&value, |(key, _)| *key).ok().map(|index| rules[index].1)
}

pub(super) fn language(base: &str, extension: &str) -> Option<&'static str> {
    if let Some(language) = exact(NAMES, base) { return Some(language); }
    // Compound suffixes precede the final extension (e.g. project.csproj.user).
    if let Some((_, language)) = SUFFIXES.iter().find(|(suffix, _)| base.ends_with(suffix)) {
        return Some(language);
    }
    if let Some(language) = exact(EXTENSIONS, extension) { return Some(language); }
    // Fold only designated extensions. In particular .c/.C and .h/.H differ.
    if let Some((_, language)) = CASE_INSENSITIVE_EXTENSIONS.iter().find(|(suffix, _)| extension.eq_ignore_ascii_case(suffix)) {
        return Some(language);
    }
    if base.eq_ignore_ascii_case("justfile") || extension.eq_ignore_ascii_case("justfile") {
        return Some("just");
    }
    // Broad filename variants lose to a recognized extension, as in Vim.
    if base.starts_with("Dockerfile.") || base.starts_with("Containerfile.") { return Some("dockerfile"); }
    if base.starts_with("Makefile.") || base.starts_with("makefile.") || base.starts_with("GNUmakefile.") { return Some("make"); }
    // Vim's shell-rc wildcard rules are deliberately lower priority than
    // recognized suffixes. Compressed artifacts must retain Text fallback.
    if !matches!(extension, "gz" | "bz2" | "Z" | "xz" | "zip" | "tgz") {
        if [".zsh", ".zlog", ".zcompdump", "zsh", "zlog"].iter().any(|prefix| base.starts_with(prefix)) { return Some("zsh"); }
        if [".bashrc", ".bash_profile", ".bash-profile", ".bash_logout", ".bash-logout", ".bash_aliases", ".bash-aliases", "bash-fc.", "bash-fc-"].iter().any(|prefix| base.starts_with(prefix)) { return Some("bash"); }
        if base.starts_with(".kshrc") { return Some("ksh"); }
        if base.starts_with(".envrc.") { return Some("sh"); }
        if base.starts_with(".profile") { return Some("sh"); }
        if base.starts_with(".tcshrc") { return Some("tcsh"); }
        if base.starts_with(".cshrc") || base.starts_with(".login") { return Some("csh"); }
    }
    base.contains("vimrc").then_some("vim")
}

const NAMES: &[(&str, &str)] = &[
    (".Rhistory", "r"),
    (".Rprofile", "r"),
    (".alias", "csh"),
    (".bash-aliases", "bash"),
    (".bash-history", "bash"),
    (".bash-logout", "bash"),
    (".bash-profile", "bash"),
    (".bash_aliases", "bash"),
    (".bash_history", "bash"),
    (".bash_logout", "bash"),
    (".bash_profile", "bash"),
    (".bashrc", "bash"),
    (".clang-format", "yaml"),
    (".clang-tidy", "yaml"),
    (".clangd", "yaml"),
    (".containerignore", "gitignore"),
    (".cshrc", "csh"),
    (".dockerignore", "gitignore"),
    (".editorconfig", "editorconfig"),
    (".emacs", "lisp"),
    (".envrc", "sh"),
    (".exrc", "vim"),
    (".fdignore", "gitignore"),
    (".gitattributes", "gitattributes"),
    (".gitconfig", "gitconfig"),
    (".gitignore", "gitignore"),
    (".gitmodules", "gitconfig"),
    (".ignore", "gitignore"),
    (".kshrc", "ksh"),
    (".login", "csh"),
    (".lua_history", "lua"),
    (".netrwhist", "vim"),
    (".npmignore", "gitignore"),
    (".ocamlinit", "ocaml"),
    (".prettierignore", "gitignore"),
    (".profile", "sh"),
    (".rgignore", "gitignore"),
    (".tcshrc", "tcsh"),
    (".vscodeignore", "gitignore"),
    (".yamllint", "yaml"),
    (".zcompdump", "zsh"),
    (".zfbfmarks", "zsh"),
    (".zlogin", "zsh"),
    (".zlogout", "zsh"),
    (".zprofile", "zsh"),
    (".zsh_history", "zsh"),
    (".zshenv", "zsh"),
    (".zshrc", "zsh"),
    ("BSDmakefile", "make"),
    ("Brewfile", "ruby"),
    ("CMakeCache.txt", "cmakecache"),
    ("CMakeLists.txt", "cmake"),
    ("COMMIT_EDITMSG", "gitcommit"),
    ("Cargo.lock", "toml"),
    ("Containerfile", "dockerfile"),
    ("Dockerfile", "dockerfile"),
    ("EDIT_DESCRIPTION", "gitcommit"),
    ("GNUmakefile", "make"),
    ("GNUmakefile.am", "automake"),
    ("Gemfile", "ruby"),
    ("Guardfile", "ruby"),
    ("Jenkinsfile", "groovy"),
    ("Kbuild", "make"),
    ("MERGE_MSG", "gitcommit"),
    ("Makefile", "make"),
    ("Makefile.am", "automake"),
    ("NOTES_EDITMSG", "gitcommit"),
    ("Pipfile", "toml"),
    ("Rakefile", "ruby"),
    ("Rprofile", "r"),
    ("Rprofile.site", "r"),
    ("SQUASH_MSG", "gitcommit"),
    ("TAG_EDITMSG", "gitcommit"),
    ("Vagrantfile", "ruby"),
    ("_clang-format", "yaml"),
    ("_exrc", "vim"),
    ("bash.bashrc", "bash"),
    ("bashrc", "bash"),
    ("build.xml", "ant"),
    ("csh.cshrc", "csh"),
    ("csh.login", "csh"),
    ("csh.logout", "csh"),
    ("dockerfile", "dockerfile"),
    ("git-rebase-todo", "gitrebase"),
    ("makefile", "make"),
    ("makefile.am", "automake"),
    ("meson.build", "meson"),
    ("meson.options", "meson"),
    ("meson_options.txt", "meson"),
    ("poetry.lock", "toml"),
    ("tcsh.login", "tcsh"),
    ("tcsh.tcshrc", "tcsh"),
    ("uv.lock", "toml"),
    ("zprofile", "zsh"),
];

const SUFFIXES: &[(&str, &str)] = &[
    (".cmake.in", "cmake"),
    (".csproj.user", "xml"),
    (".fsproj.user", "xml"),
    (".ml.cppo", "ocaml"),
    (".mli.cppo", "ocaml"),
    (".vbproj.user", "xml"),
    (".vcxproj.user", "xml"),
];

const EXTENSIONS: &[(&str, &str)] = &[
    ("C", "cpp"),
    ("Dockerfile", "dockerfile"),
    ("F", "fortran"),
    ("F03", "fortran"),
    ("F08", "fortran"),
    ("F77", "fortran"),
    ("F90", "fortran"),
    ("F95", "fortran"),
    ("FOR", "fortran"),
    ("FORTRAN", "fortran"),
    ("FPP", "fortran"),
    ("FTN", "fortran"),
    ("H", "cpp"),
    ("Rd", "rhelp"),
    ("Rmd", "rmd"),
    ("ada", "ada"),
    ("adb", "ada"),
    ("adoc", "asciidoc"),
    ("ads", "ada"),
    ("ahk", "autohotkey"),
    ("asciidoc", "asciidoc"),
    ("asd", "lisp"),
    ("ass", "ssa"),
    ("atom", "xml"),
    ("au3", "autoit"),
    ("awk", "awk"),
    ("bash", "bash"),
    ("bbl", "tex"),
    ("bib", "bib"),
    ("builder", "ruby"),
    ("c", "c"),
    ("c++", "cpp"),
    ("c++m", "cpp"),
    ("cake", "c_sharp"),
    ("cbl", "cobol"),
    ("cc", "cpp"),
    ("ccm", "cpp"),
    ("cjs", "javascript"),
    ("clj", "clojure"),
    ("cljc", "clojure"),
    ("cljs", "clojure"),
    ("cljx", "clojure"),
    ("cmake", "cmake"),
    ("cob", "cobol"),
    ("conf", "conf"),
    ("cpp", "cpp"),
    ("cppm", "cpp"),
    ("cs", "c_sharp"),
    ("csh", "csh"),
    ("csproj", "xml"),
    ("css", "css"),
    ("csv", "csv"),
    ("csx", "c_sharp"),
    ("ctp", "php"),
    ("cts", "typescript"),
    ("cu", "cuda"),
    ("cuh", "cuda"),
    ("cxx", "cpp"),
    ("cxxm", "cpp"),
    ("dart", "dart"),
    ("dash", "dash"),
    ("diff", "diff"),
    ("dockerfile", "dockerfile"),
    ("dot", "dot"),
    ("dpr", "pascal"),
    ("drt", "dart"),
    ("dtd", "dtd"),
    ("dtx", "tex"),
    ("el", "lisp"),
    ("envrc", "sh"),
    ("erb", "eruby"),
    ("erl", "erlang"),
    ("es", "javascript"),
    ("f03", "fortran"),
    ("f08", "fortran"),
    ("f77", "fortran"),
    ("f90", "fortran"),
    ("f95", "fortran"),
    ("fish", "fish"),
    ("for", "fortran"),
    ("fortran", "fortran"),
    ("fpp", "fortran"),
    ("fsproj", "xml"),
    ("ftn", "fortran"),
    ("gawk", "awk"),
    ("gd", "gdscript"),
    ("gdshader", "gdshader"),
    ("gemspec", "ruby"),
    ("geojson", "json"),
    ("go", "go"),
    ("gql", "graphql"),
    ("gradle", "groovy"),
    ("graphql", "graphql"),
    ("graphqls", "graphql"),
    ("groovy", "groovy"),
    ("gv", "dot"),
    ("gyp", "gyp"),
    ("gypi", "gyp"),
    ("h", "c"),
    ("haml", "haml"),
    ("hcl", "hcl"),
    ("hh", "cpp"),
    ("hpp", "cpp"),
    ("hrl", "erlang"),
    ("hs", "haskell"),
    ("hs-boot", "haskell"),
    ("hsc", "haskell"),
    ("hsig", "haskell"),
    ("hxx", "cpp"),
    ("inl", "cpp"),
    ("ipp", "cpp"),
    ("ipy", "python"),
    ("ipynb", "json"),
    ("itcl", "tcl"),
    ("itk", "tcl"),
    ("ixx", "cpp"),
    ("jacl", "tcl"),
    ("jav", "java"),
    ("java", "java"),
    ("javascript", "javascript"),
    ("jinja", "jinja"),
    ("jl", "julia"),
    ("jq", "jq"),
    ("js", "javascript"),
    ("jsh", "java"),
    ("jsm", "javascript"),
    ("json", "json"),
    ("json5", "json5"),
    ("jsonc", "jsonc"),
    ("jsp", "jsp"),
    ("jsx", "javascript"),
    ("ksh", "ksh"),
    ("kt", "kotlin"),
    ("ktm", "kotlin"),
    ("kts", "kotlin"),
    ("latex", "tex"),
    ("less", "less"),
    ("lhs", "lhaskell"),
    ("liquid", "liquid"),
    ("lisp", "lisp"),
    ("lsp", "lisp"),
    ("ltx", "tex"),
    ("lua", "lua"),
    ("m", "objc"),
    ("mak", "make"),
    ("markdown", "markdown"),
    ("md", "markdown"),
    ("mdown", "markdown"),
    ("mdwn", "markdown"),
    ("mermaid", "mermaid"),
    ("mjs", "javascript"),
    ("mk", "make"),
    ("mkd", "markdown"),
    ("mkdn", "markdown"),
    ("mksh", "mksh"),
    ("ml", "ocaml"),
    ("mli", "ocaml"),
    ("mll", "ocaml"),
    ("mly", "ocaml"),
    ("mm", "objc"),
    ("mts", "typescript"),
    ("ninja", "ninja"),
    ("nix", "nix"),
    ("nsh", "nsis"),
    ("nsi", "nsis"),
    ("nuspec", "xml"),
    ("pas", "pascal"),
    ("patch", "diff"),
    ("pbtxt", "pbtxt"),
    ("pdf_tex", "tex"),
    ("php", "php"),
    ("php3", "php"),
    ("php4", "php"),
    ("php5", "php"),
    ("php6", "php"),
    ("php7", "php"),
    ("php8", "php"),
    ("phpt", "php"),
    ("phtml", "php"),
    ("pl", "perl"),
    ("pm", "perl"),
    ("properties", "jproperties"),
    ("props", "xml"),
    ("proto", "proto"),
    ("ptl", "python"),
    ("pxd", "pyrex"),
    ("pxi", "pyrex"),
    ("py", "python"),
    ("pyi", "python"),
    ("pyw", "python"),
    ("pyx", "pyrex"),
    ("rake", "ruby"),
    ("rb", "ruby"),
    ("rbi", "ruby"),
    ("rbw", "ruby"),
    ("rd", "rhelp"),
    ("rej", "diff"),
    ("resx", "xml"),
    ("rhtml", "eruby"),
    ("rjs", "ruby"),
    ("rkt", "racket"),
    ("rktd", "racket"),
    ("rktl", "racket"),
    ("rmd", "rmd"),
    ("rockspec", "lua"),
    ("rs", "rust"),
    ("rss", "xml"),
    ("rst", "rst"),
    ("rtf", "rtf"),
    ("ru", "ruby"),
    ("rxml", "ruby"),
    ("sass", "sass"),
    ("scala", "scala"),
    ("scm", "scheme"),
    ("scss", "scss"),
    ("sh", "sh"),
    ("sld", "scheme"),
    ("slnf", "json"),
    ("slnx", "xml"),
    ("sql", "sql"),
    ("srt", "srt"),
    ("ss", "scheme"),
    ("ssa", "ssa"),
    ("sty", "tex"),
    ("sv", "systemverilog"),
    ("svg", "svg"),
    ("svh", "systemverilog"),
    ("swift", "swift"),
    ("swiftinterface", "swift"),
    ("targets", "xml"),
    ("tcc", "cpp"),
    ("tcl", "tcl"),
    ("tcsh", "tcsh"),
    ("texi", "texinfo"),
    ("texinfo", "texinfo"),
    ("textpb", "pbtxt"),
    ("textproto", "pbtxt"),
    ("tk", "tcl"),
    ("tlu", "lua"),
    ("toml", "toml"),
    ("tres", "gdresource"),
    ("ts", "typescript"),
    ("tscn", "gdresource"),
    ("tsv", "tsv"),
    ("tsx", "tsx"),
    ("txi", "texinfo"),
    ("txtpb", "pbtxt"),
    ("ui", "xml"),
    ("vbproj", "xml"),
    ("vcxproj", "xml"),
    ("vhd", "vhdl"),
    ("vhdl", "vhdl"),
    ("vim", "vim"),
    ("vue", "vue"),
    ("webmanifest", "json"),
    ("wsdl", "xml"),
    ("xlf", "xml"),
    ("xliff", "xml"),
    ("xmi", "xml"),
    ("xml", "xml"),
    ("xsd", "xsd"),
    ("xsl", "xslt"),
    ("xslt", "xslt"),
    ("xul", "xml"),
    ("yaml", "yaml"),
    ("yaws", "erlang"),
    ("yml", "yaml"),
    ("zig", "zig"),
    ("zon", "zig"),
    ("zsh", "zsh"),
    ("zsh-theme", "zsh"),
    ("zunit", "zsh"),
];

const CASE_INSENSITIVE_EXTENSIONS: &[(&str, &str)] = &[
    ("bat", "dosbatch"),
    ("cmd", "dosbatch"),
    ("htm", "html"),
    ("html", "html"),
    ("ini", "dosini"),
    ("just", "just"),
    ("ps1", "ps1"),
    ("ps1xml", "ps1xml"),
    ("psd1", "ps1"),
    ("psm1", "ps1"),
    ("pssc", "ps1"),
    ("shtml", "html"),
    ("vb", "vb"),
    ("vbs", "vb"),
    ("wsc", "wsh"),
    ("wsf", "wsh"),
    ("xht", "html"),
    ("xhtml", "html"),
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn filename_rules_are_sorted_unique_and_reference_bundled_languages() {
        let languages = crate::document::syntax::languages::supported_languages();
        for rules in [NAMES, SUFFIXES, EXTENSIONS, CASE_INSENSITIVE_EXTENSIONS] {
            assert!(rules.windows(2).all(|pair| pair[0].0 < pair[1].0), "rules must be sorted and unique");
            for (pattern, language) in rules {
                assert!(!pattern.is_empty() && pattern.len() <= 128 && !pattern.contains(['/', '\\']));
                assert!(languages.iter().any(|candidate| candidate.id == *language), "{pattern}: {language} is not bundled");
            }
        }
        for (extension, _) in CASE_INSENSITIVE_EXTENSIONS {
            assert!(!EXTENSIONS.iter().any(|(other, _)| extension.eq_ignore_ascii_case(other)), "overlapping extension: {extension}");
        }
    }
}
