"""Generate blittable C# declarations from Viem's deliberately simple C ABI.

Run with --check in validation. No native compiler or third-party parser needed.
Unsupported declarations fail generation instead of silently changing the ABI.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
OUTPUT = ROOT / "src/win/Interop/Native.g.cs"
source = "\n".join((ROOT / "include" / name).read_text() for name in
                   ("viem_startup.h", "viem_core.h"))
source = re.sub(r"/\*.*?\*/", "", source, flags=re.S)
source = source.replace("\\\n", "")
types = {"uint8_t": "byte", "uint16_t": "ushort", "uint32_t": "uint",
         "uint64_t": "ulong", "int32_t": "int", "int64_t": "long",
         "float": "float", "double": "double", "void": "void"}
for base, name in re.findall(r"typedef\s+(\w+)\s+(\w+)\s*;", source):
    types[name] = types[base]
for name in re.findall(r"typedef\s+\w+\s*\*?\s*\(\*(\w+)\)", source):
    types[name] = "nint"

def declaration(text):
    text = re.sub(r"\bconst\b", "", text).strip()
    match = re.fullmatch(r"(\w+)\s*(\**)\s*(\w+)(?:\[(\d+)\])?", text)
    if not match:
        raise ValueError("Unsupported C declaration: " + text)
    base, pointers, name, count = match.groups()
    return types.get(base, base) + pointers, "@" + name, count

lines = ["// <auto-generated> tools/generate_bindings.py; edit include/viem_core.h instead. </auto-generated>",
         "using System.Runtime.InteropServices;", "namespace Viem.Windows.Interop;", ""]
for name, body, end_name in re.findall(r"typedef struct (\w+)\s*\{(.*?)\}\s*(\w+)\s*;", source, re.S):
    assert name == end_name
    lines += ["[StructLayout(LayoutKind.Sequential)]", f"internal unsafe struct {name}", "{"]
    for field in body.split(";"):
        if not field.strip():
            continue
        kind, field_name, count = declaration(field)
        lines.append(f"    public {'fixed ' if count else ''}{kind} {field_name}{'[' + count + ']' if count else ''};")
    lines += ["}", ""]
lines += ["internal static unsafe partial class Native", "{"]
for name, value in re.findall(r"^#define[ \t]+(VIEM_\w+)[ \t]+([^\n]+)", source, re.M):
    value = value.strip().replace("(uint32_t)", "(uint)")
    lines.append(f"    public {'static readonly' if 'sizeof' in value else 'const'} uint {name} = {value};")

prototypes = re.findall(r"^(\w+)\s+(viem_\w+)\s*\((.*?)\)\s*;", source, re.M | re.S)
for result, name, args in prototypes:
    args = args.strip()
    parameters = []
    if args != "void":
        for arg in args.split(","):
            kind, parameter, count = declaration(arg)
            assert count is None
            parameters.append(f"{kind} {parameter}")
    lines += ['    [DllImport("viem_core", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]',
              f"    public static extern {types.get(result, result)} {name}({', '.join(parameters)});"]
lines += ["}", ""]
text = "\n".join(lines)
if "--check" in sys.argv:
    if not OUTPUT.exists() or OUTPUT.read_text() != text:
        sys.exit("C# ABI declarations are stale. Run src/win/tools/generate_bindings.py.")
else:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text)
print(f"Verified {len(prototypes)} C ABI functions" if "--check" in sys.argv else f"Generated {OUTPUT}")
