#!/usr/bin/env python3
"""Generate Viem's compact Unicode line-break properties from official data.

This is an original data parser and range packer, not a library-code import.
It uses only the Python standard library and vendored, checksum-pinned Unicode
15.0.0 data. It never downloads files. Run with --check to verify reproducibility.
"""

import argparse
from array import array
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data/unicode/15.0.0"
OUTPUT = ROOT / "src/core/layout/unicode_break_data.rs"
LIMIT = 0x110000
CLASSES = "AI AL B2 BA BB BK CB CJ CL CM CP CR EB EM EX GL H2 H3 HL HY ID IN IS JL JT JV LF NL NS NU OP PO PR QU RI SA SG SP SY WJ XX ZW ZWJ".split()
CLASS_MASK = 0x3F
EAST_ASIAN = 1 << 6
MARK = 1 << 7
UNASSIGNED_PICTOGRAPH = 1 << 8


def records(name):
    """Read Unicode's semicolon-separated ranges, ignoring comment text."""
    for number, line in enumerate((DATA / name).read_text().splitlines(), 1):
        fields = line.split("#", 1)[0].strip().split(";")
        if not fields[0]:
            continue
        assert len(fields) == 2, (name, number, line)
        endpoints = fields[0].strip().split("..")
        start = int(endpoints[0], 16)
        end = int(endpoints[-1], 16)
        assert 0 <= start <= end < LIMIT, (name, number)
        yield start, end, fields[1].strip()


def build_properties():
    # Both files explicitly include the non-global defaults for unassigned
    # CJK, emoji, and currency ranges; only XX/N remain implicit.
    values = array("H", [CLASSES.index("XX")]) * LIMIT
    seen = bytearray(LIMIT)
    for start, end, category in records("LineBreak.txt"):
        value = CLASSES.index(category)
        assert not any(seen[start : end + 1]), "overlapping line-break ranges"
        values[start : end + 1] = array("H", [value]) * (end - start + 1)
        seen[start : end + 1] = bytes([1]) * (end - start + 1)

    for start, end, category in records("EastAsianWidth.txt"):
        if category in {"F", "W", "H"}:
            for codepoint in range(start, end + 1):
                values[codepoint] |= EAST_ASIAN

    unassigned = bytearray(LIMIT)
    for start, end, category in records("DerivedGeneralCategory.txt"):
        if category == "Cn":
            unassigned[start : end + 1] = bytes([1]) * (end - start + 1)
        elif category in {"Mn", "Mc"}:
            for codepoint in range(start, end + 1):
                values[codepoint] |= MARK

    for start, end, category in records("emoji-data.txt"):
        if category == "Extended_Pictographic":
            for codepoint in range(start, end + 1):
                if unassigned[codepoint]:
                    values[codepoint] |= UNASSIGNED_PICTOGRAPH
    return values


def pack_ranges(values):
    # The low 21 bits hold a range start. The upper nine bits contain the
    # class and flags, so each run occupies four bytes with no padding.
    result = [values[0] << 21]
    for codepoint in range(1, LIMIT):
        if values[codepoint] != values[codepoint - 1]:
            result.append(codepoint | (values[codepoint] << 21))

    # Verify every code point against the unpacked source-derived values,
    # including implicit defaults and both ends of every generated range.
    starts = [entry & 0x1FFFFF for entry in result] + [LIMIT]
    for index, entry in enumerate(result):
        value = entry >> 21
        assert all(item == value for item in values[starts[index] : starts[index + 1]])
    return result


def rust_array(name, kind, values, width, columns):
    lines = ["#[rustfmt::skip]", f"const {name}: [{kind}; {len(values)}] = ["]
    for offset in range(0, len(values), columns):
        lines.append("    " + " ".join(f"0x{value:0{width}x}," for value in values[offset : offset + columns]))
    return "\n".join(lines + ["];", ""])


def render(values, ranges):
    source = '''// Generated by scripts/generate-unicode-break-data.py. Do not edit by hand.
// Unicode 15.0.0 character-property data for UAX #14 revision 49.
// The generator and lookup implementation are original Viem code.
// Source URLs, SHA-256 checksums, and Unicode data license:
// data/unicode/15.0.0/{manifest.json,LICENSE.txt,README.md}.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
#[allow(clippy::upper_case_acronyms)]
pub(super) enum LineBreakClass {
'''
    source += "".join(f"    {name},\n" for name in CLASSES)
    source += '''}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) struct CharacterProperties {
    pub(super) class: LineBreakClass,
    pub(super) east_asian_fwh: bool,
    /// General_Category Mn or Mc, as required for SA resolution in LB1.
    pub(super) mark: bool,
    /// Extended_Pictographic intersected with General_Category Cn (LB30b).
    pub(super) unassigned_extended_pictographic: bool,
}

pub(super) fn properties(character: char) -> CharacterProperties {
    let codepoint = character as u32;
    let value = if codepoint < 128 {
        ASCII[codepoint as usize]
    } else {
        // Each entry starts a range which ends immediately before the next.
        let index = RANGES.partition_point(|entry| entry & 0x1f_ffff <= codepoint) - 1;
        (RANGES[index] >> 21) as u16
    };
    CharacterProperties {
        class: CLASSES[usize::from(value & 0x3f)],
        east_asian_fwh: value & (1 << 6) != 0,
        mark: value & (1 << 7) != 0,
        unassigned_extended_pictographic: value & (1 << 8) != 0,
    }
}

'''
    source += f"const CLASSES: [LineBreakClass; {len(CLASSES)}] = [\n"
    source += "".join(f"    LineBreakClass::{name},\n" for name in CLASSES)
    source += "];\n\n"
    source += rust_array("ASCII", "u16", values[:128], 3, 8)
    source += "\n" + rust_array("RANGES", "u32", ranges, 8, 6)
    source += '''
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn property_ranges_are_sorted_and_ascii_agrees() {
        assert_eq!(RANGES[0] & 0x1f_ffff, 0);
        assert!(RANGES
            .windows(2)
            .all(|pair| pair[0] & 0x1f_ffff < pair[1] & 0x1f_ffff));
        assert!(RANGES
            .iter()
            .all(|entry| ((entry >> 21) & 0x3f) < CLASSES.len() as u32));
        for codepoint in 0..128_u32 {
            let index = RANGES.partition_point(|entry| entry & 0x1f_ffff <= codepoint) - 1;
            assert_eq!(ASCII[codepoint as usize], (RANGES[index] >> 21) as u16);
        }
    }

    #[test]
    fn unicode_defaults_and_rule_specific_flags_are_preserved() {
        assert_eq!(properties('a').class, LineBreakClass::AL);
        assert_eq!(properties('\\n').class, LineBreakClass::LF);
        assert_eq!(properties('\\u{378}').class, LineBreakClass::XX);
        assert_eq!(properties('\\u{20cf}').class, LineBreakClass::PR);
        assert_eq!(properties('\\u{2fffd}').class, LineBreakClass::ID);
        assert_eq!(properties('\\u{2fffe}').class, LineBreakClass::XX);
        assert_eq!(properties('\\u{3fffd}').class, LineBreakClass::ID);
        assert_eq!(properties('\\u{3fffe}').class, LineBreakClass::XX);
        assert!(properties('\\u{2fffd}').east_asian_fwh);
        assert!(!properties('(').east_asian_fwh);
        assert!(properties('\\u{ff08}').east_asian_fwh);
        assert!(properties('\\u{ff62}').east_asian_fwh);
        assert_eq!(properties('\\u{e31}').class, LineBreakClass::SA);
        assert!(properties('\\u{e31}').mark); // Mn
        assert!(!properties('\\u{e33}').mark); // Lo, despite its vowel role
        assert!(properties('\\u{17b6}').mark); // Mc
        assert!(!properties('\\u{20dd}').mark); // Me is deliberately excluded
        assert!(properties('\\u{1fc00}').unassigned_extended_pictographic);
        assert!(!properties('\\u{1f600}').unassigned_extended_pictographic);
        assert!(!properties('\\u{378}').unassigned_extended_pictographic);
    }
}
'''
    return source


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated output differs")
    args = parser.parse_args()
    manifest = json.loads((DATA / "manifest.json").read_text())
    assert manifest["unicode_version"] == "15.0.0" and manifest["uax14_revision"] == 49
    for name, expected in manifest["files"].items():
        content = (DATA / name).read_bytes()
        assert len(content) == expected["bytes"], f"size mismatch: {name}"
        assert hashlib.sha256(content).hexdigest() == expected["sha256"], f"checksum mismatch: {name}"
    values = build_properties()
    ranges = pack_ranges(values)
    generated = render(values, ranges)
    if args.check:
        if OUTPUT.read_text() != generated:
            raise SystemExit(f"Generated output differs: run {Path(__file__).name}")
    else:
        OUTPUT.write_text(generated)
    print(f"Unicode 15.0.0: {len(ranges)} ranges, {len(ranges) * 4 + 128 * 2 + len(CLASSES)} static bytes; verified all {LIMIT:,} code points")


if __name__ == "__main__":
    main()
